package com.laurynas.workorder.validationrest.business;

public enum ValidationResultCode {

    INVALID_DEPARTMENT,
    INVALID_START_DATE,
    INVALID_END_DATE,
    INVALID_CURRENCY,
    INVALID_COST,
    INVALID_ANALYSIS_DATE,
    MISSING_RESPONSIBLE_PERSON,
    INVALID_TEST_DATE,
    MISSING_PARTS,
    MISSING_FACTORY_NAME,
    INVALID_FACTORY_ORDER_NUMBER,
    MISSING_INVENTORY_NUMBER_ON_PARTS

}
